version: '3.5'

services:
  angularit:
    image: node:10.11.0-alpine
    volumes:
    - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
    entrypoint: sh -c "npm install && npm start"
    restart: on-failure
    ports:
      - '4200:4200'
